#!/bin/sh
set -e

# source common bashlib or exit
if [[ -f ${UKWACOMMONDIR}/common.sh ]]; then source ${UKWACOMMONDIR}/common.sh; else echo "ERROR: ${UKWACOMMONDIR}/common.sh missing"; exit 1; fi

NOPREFIX=1
DEBUG=

SERVICE=pywb
USER=$(id --user --name)
GROUP=$(id --group --name)
BASEDIR=/opt
PYWBDIR=${BASEDIR}/${SERVICE}
PYWBCFGDIR=/etc/${SERVICE}


# functions ----------
function install_pywb {
	log DEBUG "install_pywb"
	if ! [[ -d ${PYWBDIR}/ ]]; then
		log INFO "Making ${PYWBDIR} directory"
		sudo mkdir ${PYWBDIR}
		sudo chown ${USER}:${GROUP} ${PYWBDIR}

		log INFO "Create venv"
		cd ${PYWBDIR}
		python -m venv venv
		source venv/bin/activate

		log INFO "Upgrading pip"
		python -m pip install --upgrade pip

		log INFO "Installing pyuwb"
		python -m pip install pywb
	fi
	[[ -d ${PYWBCFGDIR}/ ]] || sudo mkdir ${PYWBCFGDIR}
	sudo chown ${USER}:${GROUP} ${PYWBDIR} ${PYWBCFGDIR}
}

function set_selinux {
	log DEBUG "set_selinux"
	sudo setsebool -P httpd_can_network_connect=on
}

# script -------------
ensure_not_root
install_pywb
set_selinux
copy_directory fs

log_stop
