#!/bin/env bash

# source common or die
if [[ -f ~/bin/common ]]; then source ~/bin/common; else echo "ERROR: ~/bin/common missing"; exit 1; fi


# globals -----
NOPREFIX=1
DEBUG=
ACTION=status		# default = status


# functions  -----
function get_args {
    while [[ ${#@} -gt 0 ]]; do
        local _a=$1
        log DEBUG "_a: [${_a}]"
        if [[ ${_a} == '--debug' || ${_a} == '-d' ]]; then DEBUG=${_a}
		else ACTION=$1
        fi
        shift
    done
	log DEBUG "ACTION:\t [${DEBUG}]"
}

function sysd_service {
	local _s=$1
	sudo systemctl daemon-reload
	local _response=$(sudo systemctl ${ACTION} ${_s} 2>&1)
	if [[ ${_response} =~ "could not be found" ]]; then
		log WARNING "${_s} not installed"
	else
		log INFO "${ACTION} ${_s}\n${_response}"
	fi
}

# script -----
get_args $@

sysd_service nginx
sysd_service outbackcdx
sysd_service pywb
sysd_service uwsgi
sysd_service warcserver

log INFO "\n----------------------------------------------"
ps -ef | grep -v grep | grep -P "(nginx|cdx|pywb|uwsgi|warcserver)"

log_stop
