debug: true

collections:
  archive:
    index_paths: "cdx+http://localhost:8081/fc?url={url}&closest={closest}&sort=closest&filter=!statuscode:429&filter=!mimetype:warc/revisit"
    archive_paths: http://localhost:8070/
