collections:
  archive:
    index_paths: "cdx+http://localhost:8081/fc?url={url}&closest={closest}&sort=closest"
#    archive_paths: http://localhost:8070/
    archive_paths: /mnt/s3/ukwa-fc2023-s3-1/heritrix/output/frequent-npld/20240531154350/warcs/
