collections:
  archive:
    index_paths: cdx+http://localhost:8081/fc
#    archive_paths: http://localhost:8070/
    archive_paths:
      - /mnt/s3/ukwa-fc2023-s3-1/heritrix/output/frequent-npld/20240531154350/warcs/
      - /mnt/s3/ukwa-fc2023-s3-1/heritrix/output/frequent-npld/20240820104810/warcs/
      - /mnt/s3/ukwa-fc2023-s3-1/heritrix/output/frequent-npld/20240821113600/warcs/
